### ISSUE TITLE
Knative models are not available and cannot be built

### ISSUE THREAD

**Issue by gunpuz** [IvanJosipovic/KubernetesCRDModelGen#206]
knative.dev nuget package is not available and solution fails to build Knative models

**Comment by IvanJosipovic** [comment]
Hey, yep there is a bug that I need to resolve. I will look into in the next couple days.

**Comment by gunpuz** [comment]
Actually, there seems to be issue with some of the yamls. I managed to build and convert CRDs to c# library sucessfully leaving only some CRDs that I really need and deleting those that I don't.

I managed to build with those yamls
![image](https://github.com/IvanJosipovic/KubernetesCRDModelGen/assets/39419120/17e46633-0f6e-4933-a6d9-af6a8b2770cb)

As you can see here, there are many more yamls
https://github.com/IvanJosipovic/KubernetesCRDModelGen/tree/sync-charts/src/Models/KubernetesCRDModelGen.Models.knative.dev

If this helps ;)

**Comment by IvanJosipovic** [comment]
Create a bug in the C# client, https://github.com/kubernetes-client/csharp/issues/1331

**Comment by IvanJosipovic** [comment]
Fixed locally in, https://github.com/IvanJosipovic/KubernetesCRDModelGen/commit/7e210395483f7134cb3886c1f068c852c1c310ca
